### ISSUE TITLE
Logic Behind Extracting Top 3 Amount of Time Speent in Important placces (Phone Location - Doryab Feature)

### ISSUE THREAD

**Issue by yikun-chi** [carissalow/rapids#138]
Not sure if I misunderstood the intention behind the [code](https://github.com/carissalow/rapids/blob/b3c05128fa4cb1425f13cdb395a016b537fb70d9/src/features/phone_locations/doryab/main.py#L191-L198) for getting the time spent in the top 3 clusters (Phone Location, Doryab feature).

In the current logic, if there are more than 3 clusters, the output for time spent in top1, top2, and top3 clusters are None (line 198).  Shouldn't the expected behavior be extracting the top 3 amount of times spent in the cluster instead of None? 

If I misunderstood the intention and that is the expected behavior, just let me know. Thank you!

**Comment by JulioV** [comment]
Thanks for reporting this @yikun-chi. This was a bug that we fixed in v1.3.0 that we released today. This is the new way we compute those features: https://github.com/carissalow/rapids/blob/daced51ca915a12a6129c30b50746a278ed1d915/src/features/phone_locations/doryab/main.py#L64 Let us know if you have any other questions
