### ISSUE TITLE
Documentation clarification for WiFi `countscansmostuniquedevice`

### ISSUE THREAD

**Issue by gtsherman** [carissalow/rapids#211]
Both `PHONE_WIFI_VISIBLE` and `PHONE_WIFI_CONNECTED` have the same explanation for `countscansmostuniquedevice`:

> Number of scans of the most scanned access point during a time_segment across the whole monitoring period

Does this description apply for `_CONNECTED`? Or should it be something like "Number of scans of the most **connected** access point..."?

Thanks for your help!

**Comment by jenniferfedor** [comment]
Descriptions for the phone WiFI visible and phone WiFI connected features were fixed in [`a353e58`](https://github.com/carissalow/rapids/commit/a353e58c569f7b9515900337acf80cfcb1e2f7f3). We have been working through an issue in which changes to our documentation are not being reflected on [rapids.science](rapids.science), so for now these updates are viewable in the raw markdown files or by building the docs locally.
