### ISSUE TITLE
Error in rule renv_install

### ISSUE THREAD

**Issue by svprice** [carissalow/rapids#64]
I'm attempting to set up RAPIDS, and the prior steps all worked, but I'm now coming across the following error when running "snakemake renv_install" (I added --printshellcmds for verbosity). 

The error is: "Error in rule renv_install:
    jobid: 0
    shell:
        R -e 'if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv", repos="http://cran.us.r-project.org")'
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)"

I have Ubuntu 18.04.4 LTS, and attached the full command + error message below.

![initial_error](https://user-images.githubusercontent.com/5599286/83342540-56aac080-a2b6-11ea-846e-fdf8d97f08c9.png)

I also attempted to install libicuuc.so.66 as it seemed like it was missing, but it appears like it is present:

![follow-up](https://user-images.githubusercontent.com/5599286/83342543-590d1a80-a2b6-11ea-8c38-af830e50bfed.png)

Any help resolving this would be greatly appreciated!

Thank you,
Stephen

**Comment by JulioV** [comment]
I think this is related to R and brew. Can you uninstall R using brew and then installing R 4.0 using these instructions? https://www.digitalocean.com/community/tutorials/how-to-install-r-on-ubuntu-18-04-quickstart 

I replicated this issue and after reinstalling R `snakemake renv_restore` worked on a clean VM running Ubuntu 18.04

**Comment by JulioV** [comment]
Quick update, I've run through all the installation instructions in Ubuntu 18.04 and if you find these errors while restoring r packages with renv you need the following libraries:

```
--------------------------[ ERROR MESSAGE ]----------------------------
<stdin>:1:10: fatal error: mysql.h: No such file or directory
compilation terminated.
-----------------------------------------------------------------------
ERROR: configuration failed for package ‘RMySQL’
```
Install
`sudo apt install libmariadbclient-dev`

`No package 'libcurl' found`
Install
`sudo apt install libcurl4-openssl-dev`

`Configuration failed because openssl was not found.`
Install
`sudo apt install libssl-dev`

`Configuration failed because libxml-2.0 was not found`
Install
`sudo apt install libxml2-dev`

**Comment by JulioV** [comment]
Installation instructions have been updated and tested for Ubuntu 18.04 and 20.04
