### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by IanLiu0313** [carissalow/rapids#77]
Hi, I have been experiencing this issue after running the command "snakemake -j1" The error says "CalledProcessError in line 8 of /home/ianliu/rapids/rules/preprocessing.snakefile:".

I've followed all the steps as the documentation instructs.

![CalledProcessError](https://user-images.githubusercontent.com/25919201/85965873-237a5080-b98c-11ea-8968-ef781895cff8.png)

**Comment by JulioV** [comment]
@IanLiu0313 can you paste your `.env` file without your password and the first 35 lines of you `config.yaml`, please?

**Comment by JulioV** [comment]
@IanLiu0313 The problem is Ubuntu wide when trying to connect to an old MySQL server (in this case api.awareframework.com) with MySQL client 8.0. You will get the same error message if you try to connect from the command line. There you can add the option `--ssl-mode=DISABLED` but we can't do this from the R connector. 

I talked to Denzil and it is not feasible to update api.awareframework.com at the moment as it's meant mostly for testing. The quickest solution would be to import your database to another server or to a local environment. Alternatively, you could replace `mysql-client` and `libmysqlclient-dev` with `mariadb-client` and `libmariadbclient-devinstall` and reinstall `renv`, in theory it should work but I have not tested it.

More info about this issue here https://bugs.launchpad.net/ubuntu/+source/mysql-8.0/+bug/1872541

**Comment by IanLiu0313** [comment]
That's very helpful! Thank you so much Julio!
